package csvOutput;

import java.io.FileWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;

import dbj.SqliteDBJ;
import javafx.collections.ObservableList;
import model.priceModel;
import model.productionModel;
import model.textModel;

public class csvOutput {
	public static void output() throws ClassNotFoundException, SQLException, IOException {
		ObservableList<productionModel> Datas = SqliteDBJ.searchAllData();
		ObservableList<priceModel> prices = SqliteDBJ.searchAllDataPrice();
		ObservableList<textModel> texts = SqliteDBJ.searchAllDataText();
		String text1 = "", text2 = "", text3 = "";
		for(textModel text: texts) {
			text1 = text.getText1();
			text2 = text.getText2();
			text3 = text.getText3();
		}
		FileWriter fileWriter = new FileWriter("CSV/output.csv");
		BigDecimal sellPrice = null;
		String productText;
		int i = 0;
		fileWriter.append("カテゴリ");//カテゴリId
		fileWriter.append(",");
		fileWriter.append("タイトル");//商品タイトル
		fileWriter.append(",");
		fileWriter.append("説明");//商品テキスト
		fileWriter.append(",");
		fileWriter.append("開始価格");//開始価格
		fileWriter.append(",");
		fileWriter.append("即決価格");//即決価格
		fileWriter.append(",");
		fileWriter.append("個数");//個数
		fileWriter.append(",");
		fileWriter.append("開催期間");//開催期間
		fileWriter.append(",");
		fileWriter.append("終了時間");//終了時間
		fileWriter.append(",");
		fileWriter.append("画像1の名前");//画像1の名前
		fileWriter.append(",");
		fileWriter.append("画像１のコメント");//画像１のコメント
		fileWriter.append(",");
		fileWriter.append("画像2");//画像2
		fileWriter.append(",");
		fileWriter.append("画像2のコメント");//画像2のコメント
		fileWriter.append(",");
		fileWriter.append("画像3");//画像3
		fileWriter.append(",");
		fileWriter.append("画像3のコメント");//画像3のコメント
		fileWriter.append(",");
		fileWriter.append("発送元の都道府県");//発送元の都道府県
		fileWriter.append(",");
		fileWriter.append("発送元の市町村");//発送元の市町村
		fileWriter.append(",");
		fileWriter.append("送料負担");//送料負担
		fileWriter.append(",");
		fileWriter.append("代金支払い");//代金支払い
		fileWriter.append(",");
		fileWriter.append("Yahoo簡単決済");//Yahoo簡単決済
		fileWriter.append(",");
		fileWriter.append("銀行振り込み");//銀行振り込み
		fileWriter.append(",");
		fileWriter.append("簡単取引");//簡単取引
		fileWriter.append(",");
		fileWriter.append("銀行ID1");//銀行ID1
		fileWriter.append(",");
		fileWriter.append("銀行ID2");//銀行ID2
		fileWriter.append(",");
		fileWriter.append("銀行ID3");//銀行ID3
		fileWriter.append(",");
		fileWriter.append("銀行ID4");//銀行ID4
		fileWriter.append(",");
		fileWriter.append("銀行ID5");//銀行ID5
		fileWriter.append(",");
		fileWriter.append("銀行ID6");//銀行ID6
		fileWriter.append(",");
		fileWriter.append("銀行ID7");//銀行ID7
		fileWriter.append(",");
		fileWriter.append("銀行ID8");//銀行ID8
		fileWriter.append(",");
		fileWriter.append("銀行ID9");//銀行ID9
		fileWriter.append(",");
		fileWriter.append("銀行ID10");//銀行ID10
		fileWriter.append(",");
		fileWriter.append("商品の状態");//商品の状態
		fileWriter.append(",");
		fileWriter.append("商品の状態備考");//商品の状態備考
		fileWriter.append(",");
		fileWriter.append("返品の可否");//返品の可否
		fileWriter.append(",");
		fileWriter.append("返品の可否備考");//返品の可否備考
		fileWriter.append(",");
		fileWriter.append("入札者評価制限");//入札者評価制限
		fileWriter.append(",");
		fileWriter.append("悪い評価の割合での制限");//悪い評価の割合での制限
		fileWriter.append(",");
		fileWriter.append("入札者認証制限");//入札者認証制限
		fileWriter.append(",");
		fileWriter.append("自動延長");//自動延長
		fileWriter.append(",");
		fileWriter.append("早期終了");//早期終了
		fileWriter.append(",");
		fileWriter.append("値下げ交渉");//値下げ交渉
		fileWriter.append(",");
		fileWriter.append("自動再出品");//自動再出品
		fileWriter.append(",");
		fileWriter.append("自動値下げ");//自動値下げ
		fileWriter.append(",");
		fileWriter.append("自動値下げ価格変更率");//自動値下げ価格変更率
		fileWriter.append(",");
		fileWriter.append("最低落札価格");//最低落札価格
		fileWriter.append(",");
		fileWriter.append("注目のオークション");//注目のオークション
		fileWriter.append(",");
		fileWriter.append("太字テキスト");//太字テキスト
		fileWriter.append(",");
		fileWriter.append("背景色");//背景色
		fileWriter.append(",");
		fileWriter.append("目立ちアイコン");//目立ちアイコン
		fileWriter.append(",");
		fileWriter.append("贈答品アイコン");//贈答品アイコン
		fileWriter.append(",");
		fileWriter.append("送料固定");//送料固定
		fileWriter.append(",");
		fileWriter.append("荷物の大きさ");//荷物の大きさ
		fileWriter.append(",");
		fileWriter.append("荷物の重量");//荷物の重量
		fileWriter.append(",");
		fileWriter.append("ネコポス");//ネコポス
		fileWriter.append(",");
		fileWriter.append("ネコ宅急便コンパクト");//ネコ宅急便コンパクト
		fileWriter.append(",");
		fileWriter.append("ネコ宅急便");//ネコ宅急便
		fileWriter.append(",");
		fileWriter.append("ゆうパケット");//ゆうパケット
		fileWriter.append(",");
		fileWriter.append("ゆうパック");//ゆうパック
		fileWriter.append(",");
		fileWriter.append("はこBOON");//はこBOON
		fileWriter.append(",");
		fileWriter.append("はこBOON一律送料");//はこBOON一律送料
		fileWriter.append(",");
		fileWriter.append("はこBOON北海道料金");//はこBOON北海道料金
		fileWriter.append(",");
		fileWriter.append("はこBOON沖縄料金");//はこBOON沖縄料金
		fileWriter.append(",");
		fileWriter.append("はこBOON離島料金");//はこBOON離島料金
		fileWriter.append(",");
		fileWriter.append("はこBOONmini");//はこBOONmini
		fileWriter.append(",");
		fileWriter.append("発送元店舗");//発送元店舗
		fileWriter.append(",");
		fileWriter.append("発送までの日数");//発送までの日数
		fileWriter.append(",");
		fileWriter.append("発送方法1");//発送方法1
		fileWriter.append(",");
		fileWriter.append("配送方法1全国一律価格");//配送方法1全国一律価格
		fileWriter.append(",");
		fileWriter.append("北海道料金1");//北海道料金1
		fileWriter.append(",");
		fileWriter.append("沖縄料金1");//沖縄料金1
		fileWriter.append(",");
		fileWriter.append("離島料金1");//離島料金1
		fileWriter.append(",");
		fileWriter.append("発送方法2");//発送方法2
		fileWriter.append(",");
		fileWriter.append("配送方法2全国一律価格");//配送方法2全国一律価格
		fileWriter.append(",");
		fileWriter.append("北海道料金2");//北海道料金2
		fileWriter.append(",");
		fileWriter.append("沖縄料金2");//沖縄料金2
		fileWriter.append(",");
		fileWriter.append("離島料金2");//離島料金2
		fileWriter.append(",");
		fileWriter.append("発送方法3");//発送方法3
		fileWriter.append(",");
		fileWriter.append("配送方法3全国一律価格");//配送方法3全国一律価格
		fileWriter.append(",");
		fileWriter.append("北海道料金3");//北海道料金3
		fileWriter.append(",");
		fileWriter.append("沖縄料金3");//沖縄料金3
		fileWriter.append(",");
		fileWriter.append("離島料金3");//離島料金3
		fileWriter.append(",");
		fileWriter.append("発送方法4");//発送方法4
		fileWriter.append(",");
		fileWriter.append("配送方法4全国一律価格");//配送方法4全国一律価格
		fileWriter.append(",");
		fileWriter.append("北海道料金4");//北海道料金4
		fileWriter.append(",");
		fileWriter.append("沖縄料金4");//沖縄料金4
		fileWriter.append(",");
		fileWriter.append("離島料金4");//離島料金4
		fileWriter.append(",");
		fileWriter.append("発送方法5");//発送方法5
		fileWriter.append(",");
		fileWriter.append("配送方法5全国一律価格");//配送方法5全国一律価格
		fileWriter.append(",");
		fileWriter.append("北海道料金5");//北海道料金5
		fileWriter.append(",");
		fileWriter.append("沖縄料金5");//沖縄料金5
		fileWriter.append(",");
		fileWriter.append("離島料金5");//離島料金5
		fileWriter.append(",");
		fileWriter.append("発送方法6");//発送方法6
		fileWriter.append(",");
		fileWriter.append("配送方法6全国一律価格");//配送方法6全国一律価格
		fileWriter.append(",");
		fileWriter.append("北海道料金6");//北海道料金6
		fileWriter.append(",");
		fileWriter.append("沖縄料金6");//沖縄料金6
		fileWriter.append(",");
		fileWriter.append("離島料金6");//離島料金6
		fileWriter.append(",");
		fileWriter.append("発送方法7");//発送方法7
		fileWriter.append(",");
		fileWriter.append("配送方法7全国一律価格");//配送方法7全国一律価格
		fileWriter.append(",");
		fileWriter.append("北海道料金7");//北海道料金7
		fileWriter.append(",");
		fileWriter.append("沖縄料金7");//沖縄料金7
		fileWriter.append(",");
		fileWriter.append("離島料金7");//離島料金7
		fileWriter.append(",");
		fileWriter.append("発送方法8");//発送方法8
		fileWriter.append(",");
		fileWriter.append("配送方法8全国一律価格");//配送方法8全国一律価格
		fileWriter.append(",");
		fileWriter.append("北海道料金8");//北海道料金8
		fileWriter.append(",");
		fileWriter.append("沖縄料金8");//沖縄料金8
		fileWriter.append(",");
		fileWriter.append("離島料金8");//離島料金8
		fileWriter.append(",");
		fileWriter.append("発送方法9");//発送方法9
		fileWriter.append(",");
		fileWriter.append("配送方法9全国一律価格");//配送方法9全国一律価格
		fileWriter.append(",");
		fileWriter.append("北海道料金9");//北海道料金9
		fileWriter.append(",");
		fileWriter.append("沖縄料金9");//沖縄料金9
		fileWriter.append(",");
		fileWriter.append("離島料金9");//離島料金9
		fileWriter.append(",");
		fileWriter.append("発送方法10");//発送方法10
		fileWriter.append(",");
		fileWriter.append("配送方法10全国一律価格");//配送方法10全国一律価格
		fileWriter.append(",");
		fileWriter.append("北海道料金10");//北海道料金10
		fileWriter.append(",");
		fileWriter.append("沖縄料金10");//沖縄料金10
		fileWriter.append(",");
		fileWriter.append("離島料金10");//離島料金10
		fileWriter.append(",");
		fileWriter.append("受け取り後決済サービス");//受け取り後決済サービス
		fileWriter.append(",");
		fileWriter.append("海外発送");//海外発送
		fileWriter.append(",");
		fileWriter.append("アフィリエイト");//アフィリエイト
		fileWriter.append(",");
		fileWriter.append("アフィリエイト報酬率");//アフィリエイト報酬率
		fileWriter.append(",");
		fileWriter.append("出品者情報開示前チェック");//出品者情報開示前チェック
		fileWriter.append("\r\n");
		for(productionModel Data :Datas) {
			if(!Data.getPrice().equals("")){
				for(priceModel price :prices) {
					if(Integer.parseInt(Data.getPrice()) < price.getPrice()) {
						BigDecimal priceData1 = new BigDecimal(Data.getPrice());
						BigDecimal priceData2 = new BigDecimal(price.getCallPrice());
						sellPrice = priceData1.multiply(priceData2).setScale(0, BigDecimal.ROUND_UP);
						break;
					}
				}
			}
			if(!Data.getPrice().equals("") || Data.getPrice().length() != 0) {
				i = i + 1;
				productText = makeText.outputText(Data.getName(), Data.getMemo().replace(",", ""), text1, text2, text3);
				fileWriter.append(Data.getCategoryId());//カテゴリId
				fileWriter.append(",");
				fileWriter.append(Data.getName().replace(",", ""));//商品タイトル
				fileWriter.append(",");
				fileWriter.append(productText.replace(",", ""));//商品テキスト
				fileWriter.append(",");
				fileWriter.append(sellPrice.toString());//開始価格
				fileWriter.append(",");
				fileWriter.append("");//即決価格
				fileWriter.append(",");
				fileWriter.append("1");//個数
				fileWriter.append(",");
				fileWriter.append("1");//開催期間
				fileWriter.append(",");
				fileWriter.append("22");//終了時間
				fileWriter.append(",");
				fileWriter.append(Data.getImage());//画像1の名前
				fileWriter.append(",");
				fileWriter.append("");//画像１のコメント
				fileWriter.append(",");
				fileWriter.append("");//画像2
				fileWriter.append(",");
				fileWriter.append("");//画像2のコメント
				fileWriter.append(",");
				fileWriter.append("");//画像3
				fileWriter.append(",");
				fileWriter.append("");//画像3のコメント
				fileWriter.append(",");
				fileWriter.append("東京都");//発送元の都道府県
				fileWriter.append(",");
				fileWriter.append("");//発送元の市町村
				fileWriter.append(",");
				fileWriter.append("出品者");//送料負担
				fileWriter.append(",");
				fileWriter.append("先払い");//代金支払い
				fileWriter.append(",");
				fileWriter.append("はい");//Yahoo簡単決済
				fileWriter.append(",");
				fileWriter.append("いいえ");//銀行振り込み
				fileWriter.append(",");
				fileWriter.append("はい");//簡単取引
				fileWriter.append(",");
				fileWriter.append("");//銀行ID1
				fileWriter.append(",");
				fileWriter.append("");//銀行ID2
				fileWriter.append(",");
				fileWriter.append("");//銀行ID3
				fileWriter.append(",");
				fileWriter.append("");//銀行ID4
				fileWriter.append(",");
				fileWriter.append("");//銀行ID5
				fileWriter.append(",");
				fileWriter.append("");//銀行ID6
				fileWriter.append(",");
				fileWriter.append("");//銀行ID7
				fileWriter.append(",");
				fileWriter.append("");//銀行ID8
				fileWriter.append(",");
				fileWriter.append("");//銀行ID9
				fileWriter.append(",");
				fileWriter.append("");//銀行ID10
				fileWriter.append(",");
				fileWriter.append("未使用に近い");//商品の状態
				fileWriter.append(",");
				fileWriter.append("");//商品の状態備考
				fileWriter.append(",");
				fileWriter.append("返品不可");//返品の可否
				fileWriter.append(",");
				fileWriter.append("");//返品の可否備考
				fileWriter.append(",");
				fileWriter.append("いいえ");//入札者評価制限
				fileWriter.append(",");
				fileWriter.append("いいえ");//悪い評価の割合での制限
				fileWriter.append(",");
				fileWriter.append("いいえ");//入札者認証制限
				fileWriter.append(",");
				fileWriter.append("はい");//自動延長
				fileWriter.append(",");
				fileWriter.append("はい");//早期終了
				fileWriter.append(",");
				fileWriter.append("いいえ");//値下げ交渉
				fileWriter.append(",");
				fileWriter.append("3");//自動再出品
				fileWriter.append(",");
				fileWriter.append("いいえ");//自動値下げ
				fileWriter.append(",");
				fileWriter.append("");//自動値下げ価格変更率
				fileWriter.append(",");
				fileWriter.append("");//最低落札価格
				fileWriter.append(",");
				fileWriter.append("");//注目のオークション
				fileWriter.append(",");
				fileWriter.append("いいえ");//太字テキスト
				fileWriter.append(",");
				fileWriter.append("いいえ");//背景色
				fileWriter.append(",");
				fileWriter.append("");//目立ちアイコン
				fileWriter.append(",");
				fileWriter.append("いいえ");//贈答品アイコン
				fileWriter.append(",");
				fileWriter.append("はい");//送料固定
				fileWriter.append(",");
				fileWriter.append("");//荷物の大きさ
				fileWriter.append(",");
				fileWriter.append("");//荷物の重量
				fileWriter.append(",");
				fileWriter.append("いいえ");//ネコポス
				fileWriter.append(",");
				fileWriter.append("いいえ");//ネコ宅急便コンパクト
				fileWriter.append(",");
				fileWriter.append("いいえ");//ネコ宅急便
				fileWriter.append(",");
				fileWriter.append("いいえ");//ゆうパケット
				fileWriter.append(",");
				fileWriter.append("いいえ");//ゆうパック
				fileWriter.append(",");
				fileWriter.append("いいえ");//はこBOON
				fileWriter.append(",");
				fileWriter.append("");//はこBOON一律送料
				fileWriter.append(",");
				fileWriter.append("");//はこBOON北海道料金
				fileWriter.append(",");
				fileWriter.append("");//はこBOON沖縄料金
				fileWriter.append(",");
				fileWriter.append("");//はこBOON離島料金
				fileWriter.append(",");
				fileWriter.append("いいえ");//はこBOONmini
				fileWriter.append(",");
				fileWriter.append("");//発送元店舗
				fileWriter.append(",");
				fileWriter.append("3日～6日");//発送までの日数
				fileWriter.append(",");
				fileWriter.append("配送委託会社にて一律料金");//発送方法1
				fileWriter.append(",");
				fileWriter.append("0");//配送方法1全国一律価格
				fileWriter.append(",");
				fileWriter.append("");//北海道料金1
				fileWriter.append(",");
				fileWriter.append("");//沖縄料金1
				fileWriter.append(",");
				fileWriter.append("");//離島料金1
				fileWriter.append(",");
				fileWriter.append("");//発送方法2
				fileWriter.append(",");
				fileWriter.append("");//配送方法2全国一律価格
				fileWriter.append(",");
				fileWriter.append("");//北海道料金2
				fileWriter.append(",");
				fileWriter.append("");//沖縄料金2
				fileWriter.append(",");
				fileWriter.append("");//離島料金2
				fileWriter.append(",");
				fileWriter.append("");//発送方法3
				fileWriter.append(",");
				fileWriter.append("");//配送方法3全国一律価格
				fileWriter.append(",");
				fileWriter.append("");//北海道料金3
				fileWriter.append(",");
				fileWriter.append("");//沖縄料金3
				fileWriter.append(",");
				fileWriter.append("");//離島料金3
				fileWriter.append(",");
				fileWriter.append("");//発送方法4
				fileWriter.append(",");
				fileWriter.append("");//配送方法4全国一律価格
				fileWriter.append(",");
				fileWriter.append("");//北海道料金4
				fileWriter.append(",");
				fileWriter.append("");//沖縄料金4
				fileWriter.append(",");
				fileWriter.append("");//離島料金4
				fileWriter.append(",");
				fileWriter.append("");//発送方法5
				fileWriter.append(",");
				fileWriter.append("");//配送方法5全国一律価格
				fileWriter.append(",");
				fileWriter.append("");//北海道料金5
				fileWriter.append(",");
				fileWriter.append("");//沖縄料金5
				fileWriter.append(",");
				fileWriter.append("");//離島料金5
				fileWriter.append(",");
				fileWriter.append("");//発送方法6
				fileWriter.append(",");
				fileWriter.append("");//配送方法6全国一律価格
				fileWriter.append(",");
				fileWriter.append("");//北海道料金6
				fileWriter.append(",");
				fileWriter.append("");//沖縄料金6
				fileWriter.append(",");
				fileWriter.append("");//離島料金6
				fileWriter.append(",");
				fileWriter.append("");//発送方法7
				fileWriter.append(",");
				fileWriter.append("");//配送方法7全国一律価格
				fileWriter.append(",");
				fileWriter.append("");//北海道料金7
				fileWriter.append(",");
				fileWriter.append("");//沖縄料金7
				fileWriter.append(",");
				fileWriter.append("");//離島料金7
				fileWriter.append(",");
				fileWriter.append("");//発送方法8
				fileWriter.append(",");
				fileWriter.append("");//配送方法8全国一律価格
				fileWriter.append(",");
				fileWriter.append("");//北海道料金8
				fileWriter.append(",");
				fileWriter.append("");//沖縄料金8
				fileWriter.append(",");
				fileWriter.append("");//離島料金8
				fileWriter.append(",");
				fileWriter.append("");//発送方法9
				fileWriter.append(",");
				fileWriter.append("");//配送方法9全国一律価格
				fileWriter.append(",");
				fileWriter.append("");//北海道料金9
				fileWriter.append(",");
				fileWriter.append("");//沖縄料金9
				fileWriter.append(",");
				fileWriter.append("");//離島料金9
				fileWriter.append(",");
				fileWriter.append("");//発送方法10
				fileWriter.append(",");
				fileWriter.append("");//配送方法10全国一律価格
				fileWriter.append(",");
				fileWriter.append("");//北海道料金10
				fileWriter.append(",");
				fileWriter.append("");//沖縄料金10
				fileWriter.append(",");
				fileWriter.append("");//離島料金10
				fileWriter.append(",");
				fileWriter.append("いいえ");//受け取り後決済サービス
				fileWriter.append(",");
				fileWriter.append("いいえ");//海外発送
				fileWriter.append(",");
				fileWriter.append("いいえ");//アフィリエイト
				fileWriter.append(",");
				fileWriter.append("");//アフィリエイト報酬率
				fileWriter.append(",");
				fileWriter.append("いいえ");//出品者情報開示前チェック
				fileWriter.append("\r\n");
			}
		}
		try {
	        fileWriter.flush();
	        fileWriter.close();
	      } catch (IOException e) {
	        e.printStackTrace();
	      }
	}

}
